// Generated by CoffeeScript 1.7.1
(function() {
  var isNoN, path;

  path = require('path');

  isNoN = function(non) {
    var json, re, serif, _i, _len;
    if (typeof non !== 'string') {
      return false;
    }
    json = require('./serifexps');
    for (_i = 0, _len = json.length; _i < _len; _i++) {
      serif = json[_i];
      re = new RegExp(serif);
      if (non.match(re)) {
        return true;
      }
    }
    return false;
  };

  module.exports = isNoN;

}).call(this);
